import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    CornerRightUp,
    Leaf,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    SunMoon,
    Trash,
    User,
    X,
    Github,
    type LucideIcon,
  } from "lucide-react"
  
  export type Icon = LucideIcon
  
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    arrowRightUp: CornerRightUp,
    help: HelpCircle,
    pizza: Pizza,
    leaf: Leaf,
    sun: SunMedium,
    moon: Moon,
    solarEclipse: SunMoon,
    laptop: Laptop,
    gitHub: Github,
    check: Check,
  }